CREATE TABLE student (
  STDID INT PRIMARY KEY,
  SNAME VARCHAR(50)
);

CREATE TABLE CORSE (
  Cid INT PRIMARY KEY,
  Cname VARCHAR(50)
);
CREATE TABLE STDCRS (
  STDID INT PRIMARY KEY,
 Cid INT PRIMARY KEY
);