--one to one total participation and partial
CREATE TABLE EMPLOYEE (
EID INT PRIMARY KEY,
ENAME VARCHAR(50)
);
CREATE TABLE COMPUTER (
CID INT PRIMARY KEY,
CNAME VARCHAR(50),
EID INT  FOREIGN KEY (EID) REFERENCES EMPLOYEE(EID)
);